@startuml
宿主业务 -> 接口组件: 触发输入事件，带入消息
接口组件 -> 消息分配器: 将消息传给分配器
消息分配器 -> 影子设备: 根据消息类型和ID传给具体设备
影子设备 -> 编解码器: 根据型号调用编解码
编解码器 -> 影子设备: 返回编解码后的结果
影子设备 -> 消息分配器: 返回消息给分配器
消息分配器 -> 接口组件: 返回消息给组件
接口组件 -> 宿主业务: 触发输出事件，传出消息
@enduml